--- # User config
user_config:
  ssh_username: automate
  ssh_password: automateme
  path_to_csv_file:
  ssh_port:
  ssh_timeout:
  number_of_worker_threads:
  debug_mode:
  skip_ssh_reachability_check:
  skip_ssh_authentication_check:

default_config: # Default Config - don´t change any values here, edit the user config above
  path_to_csv_file: D:\Downloads\cisco-tools-csv.csv
  ssh_port: 22
  ssh_timeout: 2
  number_of_worker_threads: 8
  debug_mode: False
  skip_ssh_reachability_check: False
  skip_ssh_authentication_check: False