--- # Internal Config. Don´t change any value, unless you know what you´re doing!
interface_eth_search:
  input_file: switchlist.csv
  output_needs_parse: True
  parse_pattern: ^(interface.*)\n((?:.*\n)+?)!
  raw_output: raw_output/interface_eth_config
  results: results/
