--- # Global Config
global_config:
  ssh_username:
  ssh_password:
  path_to_csv_file: switchlist.csv
  ssh_port: 22
  ssh_timeout: 2
  number_of_worker_threads: 15
  debug_mode: False
  skip_ssh_reachability_check: False
  skip_ssh_authentication_check: False
  #Possible values: csv, prime
  input_source: csv

# Set values for this config, if you want to use Cisco Prime Infrastructure as your input source. Don't forget to change 'input_source' in the global_config.
prime_config:
  username:
  password:
  address:
  group: